services:
  - type: web
    name: whatsapp-wa-automate-server
    runtime: node
    nodeVersion: 18
    region: singapore

    buildCommand: |
      apt-get update
      apt-get install -y chromium
      npm install

    startCommand: node server.js

    envVars:
      - key: PORT
        value: 3001

    disk:
      name: whatsapp-session
      mountPath: /session
      sizeGB: 1
